{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "happy.fullname" . }}-ui
  labels:
    {{- include "happy.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "happy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
{{- end }}
