apiVersion: v2
name: example-app
description: A generic example Helm chart demonstrating repository conventions
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - example
  - web
  - application
home: https://github.com/denysvitali/charts
sources:
  - https://github.com/denysvitali/charts
maintainers:
  - name: denysvitali
    url: https://github.com/denysvitali
